USE [master]
GO

/****** Object:  Database [HRSManagement]    Script Date: 26-09-2017 04:12:03 PM ******/
CREATE DATABASE [HRSManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HRSManagement', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\HRSManagement.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HRSManagement_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\HRSManagement_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HRSManagement] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HRSManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HRSManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HRSManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HRSManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HRSManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HRSManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [HRSManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HRSManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HRSManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HRSManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HRSManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HRSManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HRSManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HRSManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HRSManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HRSManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HRSManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HRSManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HRSManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HRSManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HRSManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HRSManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HRSManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HRSManagement] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HRSManagement] SET  MULTI_USER 
GO

ALTER DATABASE [HRSManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HRSManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HRSManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HRSManagement] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HRSManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HRSManagement] SET  READ_WRITE 
GO

